# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: HOME
    url: home
    weight: 10

  - name: RESEARCH
    url: research
    weight: 20

  - name: MEMBERS
    identifier: members
    weight: 30
  - name: CURRENT
    parent: members
    url: people
    weight: 31
  - name: GRADUATED
    parent: members
    url: graduated
    weight: 32

  - name: PROJECTS
    url: project
    weight: 40

  - name: PUBLICATIONS
    url: publication
    weight: 50

  - name: NEWS
    url: news
    weight: 60

  - name: Contact
    url: contact
    weight: 70